# Generated by Django 5.1.3 on 2024-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
