# Generated by Django 5.1.3 on 2024-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
